# Generated by Django 5.0.14 on 2025-06-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdOrderOms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insdatenew', models.CharField(blank=True, db_column='insdateNew', max_length=4000, null=True)),
                ('jobno_oms', models.CharField(db_column='Jobno Oms', max_length=50)),
                ('jobnoomsnew', models.CharField(blank=True, db_column='JobnoOmsnew', max_length=50, null=True)),
                ('mainimagepath', models.CharField(blank=True, max_length=511, null=True)),
                ('ordimg1_pen', models.CharField(db_column='OrdImg1_Pen', max_length=9)),
                ('styleid', models.IntegerField()),
                ('final_delivery_date', models.CharField(blank=True, db_column='Final delivery date', max_length=4000, null=True)),
                ('finaldelvdate1', models.DateTimeField(blank=True, null=True)),
                ('year', models.CharField(blank=True, db_column='Year', max_length=4000, null=True)),
                ('final_year_delivery', models.CharField(blank=True, db_column='Final Year delivery', max_length=4000, null=True)),
                ('final_year_delivery1', models.CharField(blank=True, db_column='Final Year delivery1', max_length=4000, null=True)),
                ('ddays', models.IntegerField(blank=True, null=True)),
                ('fdays', models.IntegerField(blank=True, db_column='Fdays', null=True)),
                ('insdays', models.IntegerField(blank=True, null=True)),
                ('finaldelvdate', models.CharField(blank=True, db_column='FinalDelvDate', max_length=4000, null=True)),
                ('ourdeldate', models.CharField(blank=True, db_column='Ourdeldate', max_length=4000, null=True)),
                ('date', models.CharField(blank=True, db_column='Date', max_length=4000, null=True)),
                ('ourdelvdate', models.CharField(blank=True, db_column='OurDelvDate', max_length=4000, null=True)),
                ('podate', models.CharField(blank=True, db_column='PODate', max_length=4000, null=True)),
                ('vessel_dt', models.CharField(blank=True, max_length=4000, null=True)),
                ('vessel_yr', models.CharField(blank=True, max_length=4000, null=True)),
                ('pono', models.CharField(blank=True, db_column='PONo', max_length=50, null=True)),
                ('shipmentcompleted', models.SmallIntegerField(db_column='ShipmentCompleted')),
                ('reference', models.CharField(blank=True, max_length=2100, null=True)),
                ('no', models.CharField(db_column='No', max_length=50)),
                ('company_name', models.CharField(blank=True, db_column='Company Name', max_length=50, null=True)),
                ('mer_un', models.CharField(blank=True, max_length=71, null=True)),
                ('image_order', models.CharField(blank=True, db_column='Image Order', max_length=4000, null=True)),
                ('abc', models.CharField(blank=True, db_column='ABC', max_length=1, null=True)),
                ('order_follow_up', models.CharField(db_column='Order_Follow_up', max_length=35)),
                ('quality_controller', models.CharField(db_column='Quality Controller', max_length=35)),
                ('buyer_sh', models.CharField(blank=True, db_column='Buyer_sh', max_length=10, null=True)),
                ('punit_sh', models.CharField(blank=True, db_column='PUnit_sh', max_length=6, null=True)),
                ('insdateyear', models.CharField(blank=True, db_column='insdateYear', max_length=4000, null=True)),
                ('insdate', models.CharField(blank=True, db_column='Insdate', max_length=4000, null=True)),
                ('quantity', models.IntegerField(blank=True, db_column='Quantity', null=True)),
                ('buyer', models.CharField(blank=True, db_column='Buyer', max_length=15, null=True)),
                ('merch', models.CharField(blank=True, max_length=35, null=True)),
                ('u46', models.CharField(blank=True, max_length=750, null=True)),
                ('actdaten', models.DateTimeField(blank=True, db_column='actdateN', null=True)),
                ('actdate', models.CharField(blank=True, db_column='Actdate', max_length=4000, null=True)),
                ('actyeardate', models.CharField(blank=True, db_column='Actyeardate', max_length=4000, null=True)),
                ('con_actdate', models.CharField(blank=True, db_column='Con_Actdate', max_length=4000, null=True)),
                ('production_unit', models.CharField(blank=True, db_column='Production_unit', max_length=35, null=True)),
                ('director_sample_order', models.CharField(db_column='Director_Sample_Order', max_length=6)),
                ('z_o_ordfol_qualitycon', models.CharField(blank=True, db_column='Z_O_Ordfol_Qualitycon', max_length=72, null=True)),
                ('con_ordno_mer_buy', models.CharField(blank=True, db_column='Con_ordno_mer_buy', max_length=95, null=True)),
                ('con_ord_un_buy_mer_sty_qty', models.CharField(blank=True, db_column='Con_ord_un_buy_mer_sty_Qty', max_length=173, null=True)),
                ('z_o_dd_ord_findt_buy_mer_qty', models.CharField(blank=True, db_column='Z_O_DD_Ord_Findt_Buy_mer_Qty', max_length=4000, null=True)),
                ('z_o_yy_findt_dir_sty_uom_pty', models.CharField(blank=True, db_column='Z_O_yy_Findt_dir_sty_uom_pty', max_length=4000, null=True)),
                ('con_str_sty_uom_prodty', models.CharField(blank=True, db_column='Con_Str_Sty_UOM_Prodty', max_length=22, null=True)),
                ('con_findt_ordno_dir_un_buy_uom_qty_mer', models.CharField(blank=True, db_column='Con_Findt_ordno_dir_un_Buy_Uom_Qty_mer', max_length=4000, null=True)),
                ('production_type_inside_outside', models.CharField(blank=True, db_column='Production_type_Inside_Outside', max_length=7, null=True)),
                ('shipment_complete', models.CharField(blank=True, db_column='Shipment_complete', max_length=9, null=True)),
            ],
            options={
                'db_table': 'Ord_Order_Oms',
                'managed': False,
            },
        ),
    ]
