# Generated by Django 5.0.14 on 2025-06-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bala', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpAttendanceFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_emb_attendance_fact', models.IntegerField(blank=True, db_column='Code Emb Attendance Fact', null=True)),
                ('date', models.DateTimeField(blank=True, db_column='Date', null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('intime', models.DateTimeField(blank=True, null=True)),
                ('outtime', models.DateTimeField(blank=True, null=True)),
                ('emppic', models.CharField(blank=True, db_column='Emppic', max_length=8000, null=True)),
                ('con_code_name_in_out', models.CharField(blank=True, db_column='Con_Code_name_in_out', max_length=4000, null=True)),
                ('rel_code_name', models.CharField(blank=True, db_column='Rel_code_name', max_length=112, null=True)),
            ],
            options={
                'db_table': 'Emp_Attendance_Fact',
                'managed': False,
            },
        ),
    ]
