# Generated by Django 5.0.14 on 2025-06-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bala', '0003_allotpen_ordsamplestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabRgbMatrplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tbimg', models.CharField(blank=True, max_length=8000, null=True)),
                ('jobno', models.CharField(db_column='Jobno', max_length=50)),
                ('combocolor', models.CharField(blank=True, db_column='ComboColor', max_length=50, null=True)),
                ('mp', models.CharField(blank=True, max_length=50, null=True)),
                ('ip', models.CharField(blank=True, max_length=50, null=True)),
                ('dyeclr', models.CharField(blank=True, db_column='Dyeclr', max_length=50, null=True)),
                ('prnclr', models.CharField(blank=True, db_column='Prnclr', max_length=50, null=True)),
                ('gsm', models.IntegerField(db_column='GSM')),
                ('fdia', models.CharField(blank=True, db_column='Fdia', max_length=70, null=True)),
                ('kdia', models.CharField(max_length=35)),
                ('pcswgt', models.CharField(blank=True, max_length=70, null=True)),
                ('size', models.CharField(max_length=35)),
                ('losspercent', models.DecimalField(db_column='LossPercent', decimal_places=2, max_digits=5)),
                ('quantity', models.DecimalField(blank=True, db_column='Quantity', decimal_places=4, max_digits=38, null=True)),
                ('fabricno', models.IntegerField(db_column='FabricNo')),
                ('ord_image', models.CharField(blank=True, db_column='Ord_image', max_length=8000, null=True)),
                ('hex', models.CharField(blank=True, max_length=15, null=True)),
                ('fimage', models.CharField(db_column='Fimage', max_length=8000)),
                ('fabty', models.CharField(blank=True, db_column='FabTy', max_length=35, null=True)),
                ('withoutfabimg', models.CharField(db_column='WithOutFabImg', max_length=13)),
                ('withoutrgb', models.CharField(db_column='WithOutRGB', max_length=10)),
                ('fabric', models.CharField(db_column='Fabric', max_length=35)),
                ('yarninfo', models.CharField(blank=True, db_column='YarnInfo', max_length=971, null=True)),
                ('ll', models.CharField(max_length=114)),
                ('con_dyeclr_prnclr', models.CharField(blank=True, db_column='Con_dyeclr_prnclr', max_length=102, null=True)),
                ('con_ord_clr_fab', models.CharField(blank=True, db_column='Con_Ord_Clr_Fab', max_length=139, null=True)),
                ('withoutll', models.CharField(max_length=9)),
                ('o_buyer', models.CharField(blank=True, db_column='O_Buyer', max_length=40, null=True)),
                ('o_merch', models.CharField(blank=True, db_column='O_Merch', max_length=35, null=True)),
                ('o_productionunit', models.CharField(blank=True, db_column='O_ProductionUnit', max_length=35, null=True)),
                ('o_ordtype', models.CharField(db_column='O_OrdType', max_length=6)),
                ('o_prodtype', models.CharField(db_column='O_ProdType', max_length=7)),
                ('con', models.CharField(blank=True, db_column='Con', max_length=193, null=True)),
                ('o_styledesc', models.CharField(blank=True, db_column='o_StyleDesc', max_length=35, null=True)),
                ('director', models.CharField(max_length=35)),
                ('planned', models.IntegerField(db_column='Planned')),
            ],
            options={
                'db_table': 'Fab_RGB_matrplan',
                'managed': False,
            },
        ),
    ]
