# Generated by Django 5.0.14 on 2025-06-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gopal', '0002_ordstk'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabYarn',
            fields=[
                ('rate_weight', models.DecimalField(db_column='Rate_Weight', decimal_places=4, max_digits=19)),
                ('img_fpath', models.CharField(blank=True, db_column='Img_Fpath', max_length=8000, null=True)),
                ('fabimg_pen', models.CharField(blank=True, db_column='Fabimg_pen', max_length=67, null=True)),
                ('fabty', models.CharField(db_column='Fabty', max_length=35)),
                ('supplier', models.CharField(max_length=35)),
                ('orderno', models.CharField(max_length=50)),
                ('clr', models.CharField(max_length=50)),
                ('fabric', models.CharField(max_length=35)),
                ('prs', models.CharField(max_length=35)),
                ('kg', models.IntegerField(blank=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ty', models.IntegerField()),
                ('hex', models.CharField(max_length=15)),
                ('kw', models.CharField(max_length=1)),
                ('dia', models.CharField(blank=True, max_length=35, null=True)),
                ('image_order', models.CharField(blank=True, db_column='Image Order', max_length=4000, null=True)),
                ('finaldia', models.CharField(blank=True, db_column='FinalDia', max_length=70, null=True)),
            ],
            options={
                'db_table': 'Fab_Yarn',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='OrdStk',
        ),
    ]
