# Generated by Django 5.0.14 on 2025-06-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gopal', '0003_fabyarn_delete_ordstk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employeelogin',
            fields=[
                ('code', models.IntegerField(db_column='Code', primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Name', max_length=50)),
                ('hod', models.BooleanField(db_column='HOD')),
                ('hodid', models.IntegerField(blank=True, db_column='HODID', null=True)),
                ('password', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Password', max_length=50, null=True)),
                ('email', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Email', max_length=100, null=True, unique=True)),
                ('ot', models.BooleanField(db_column='OT')),
            ],
            options={
                'db_table': 'EmployeeLogin',
                'managed': False,
            },
        ),
    ]
