# Generated by Django 5.0.14 on 2025-06-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllotOrderKisbal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderno', models.CharField(db_column='OrderNo', max_length=50)),
                ('colour', models.CharField(db_column='Colour', max_length=50)),
                ('sizes', models.CharField(blank=True, db_column='Sizes', max_length=35, null=True)),
                ('totalquantity', models.IntegerField(blank=True, db_column='TotalQuantity', null=True)),
                ('jobnoomsnew', models.CharField(blank=True, db_column='JobnoOmsnew', max_length=50, null=True)),
                ('orderimage', models.CharField(blank=True, db_column='OrderImage', max_length=4000, null=True)),
                ('part', models.CharField(db_column='Part', max_length=50)),
                ('tbimage', models.CharField(blank=True, db_column='TBImage', max_length=8000, null=True)),
                ('oms_supplier', models.CharField(blank=True, db_column='OMS_Supplier', max_length=35, null=True)),
                ('alloted_unit', models.CharField(blank=True, db_column='Alloted_Unit', max_length=100, null=True)),
                ('quantity', models.IntegerField(blank=True, db_column='Quantity', null=True)),
                ('allotqty', models.IntegerField(blank=True, null=True)),
                ('buyer', models.CharField(blank=True, db_column='Buyer', max_length=40, null=True)),
                ('merch', models.CharField(blank=True, db_column='Merch', max_length=35, null=True)),
                ('omscol', models.CharField(max_length=50)),
                ('omstb', models.CharField(max_length=50)),
                ('alttb', models.CharField(blank=True, max_length=70, null=True)),
                ('altclr', models.CharField(blank=True, max_length=70, null=True)),
                ('u46', models.CharField(max_length=750)),
                ('u45141', models.CharField(blank=True, max_length=1, null=True)),
                ('u50', models.CharField(blank=True, max_length=750, null=True)),
                ('date', models.CharField(blank=True, db_column='Date', max_length=4000, null=True)),
                ('podate', models.CharField(blank=True, db_column='Podate', max_length=4000, null=True)),
                ('dateyear', models.CharField(blank=True, db_column='Dateyear', max_length=4000, null=True)),
                ('podateyear', models.CharField(blank=True, max_length=4000, null=True)),
                ('con', models.CharField(blank=True, db_column='Con', max_length=191, null=True)),
                ('con_stk', models.CharField(blank=True, db_column='Con_Stk', max_length=293, null=True)),
                ('finalyeardelivery', models.CharField(blank=True, db_column='FinalYearDelivery', max_length=4000, null=True)),
                ('finaldeldate', models.CharField(blank=True, db_column='Finaldeldate', max_length=4000, null=True)),
                ('actdate', models.CharField(blank=True, db_column='Actdate', max_length=4000, null=True)),
                ('actyeardate', models.CharField(blank=True, db_column='Actyeardate', max_length=4000, null=True)),
                ('con_actdate', models.CharField(blank=True, db_column='Con_Actdate', max_length=4000, null=True)),
                ('buyer_sh', models.CharField(blank=True, db_column='Buyer_sh', max_length=6, null=True)),
                ('punit_sh', models.CharField(blank=True, db_column='Punit_sh', max_length=6, null=True)),
                ('director_sample_order', models.CharField(db_column='Director_Sample_Order', max_length=6)),
                ('production_type_inside_outside', models.CharField(blank=True, db_column='Production_type_Inside_Outside', max_length=7, null=True)),
                ('z_o_yy_findt_dir_sty_uom_pty', models.CharField(blank=True, db_column='Z_O_yy_Findt_dir_sty_uom_pty', max_length=4000, null=True)),
                ('allot_con_yy_findt_ordno_mer_punit_aqty', models.CharField(blank=True, db_column='Allot_Con_yy_Findt_Ordno_mer_PUnit_aqty', max_length=4000, null=True)),
                ('con_ord_col_tb_f', models.CharField(blank=True, db_column='Con_Ord_col_tb_f', max_length=4000, null=True)),
                ('con_ord_col_siz', models.CharField(blank=True, db_column='Con_Ord_col_siz', max_length=139, null=True)),
                ('con_ord_col_siz_unit', models.CharField(blank=True, db_column='Con_Ord_col_siz_Unit', max_length=147, null=True)),
                ('con_part_clr', models.CharField(blank=True, db_column='Con_Part_clr', max_length=102, null=True)),
                ('con_part_clr_altunit_altqty_fdel', models.CharField(blank=True, db_column='Con_Part_clr_altunit_altqty_fdel', max_length=4000, null=True)),
                ('con_ord_unit', models.CharField(blank=True, db_column='Con_ord_unit', max_length=58, null=True)),
                ('con_tot', models.CharField(blank=True, db_column='Con_tot', max_length=213, null=True)),
            ],
            options={
                'db_table': 'Allot_Order_KisBal',
                'managed': False,
            },
        ),
    ]
