# Generated by Django 5.0.14 on 2025-07-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pivot_Tabel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpLogin',
            fields=[
                ('code', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('hod', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('password', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Password', max_length=100, null=True)),
                ('emailid', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='EmailID', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Employee_Login',
                'managed': False,
            },
        ),
    ]
