# Generated by Django 5.0.14 on 2025-07-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gopal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdStk',
            fields=[
                ('trstype', models.CharField(db_column='Trstype', max_length=6)),
                ('total', models.IntegerField(blank=True, db_column='Total', null=True)),
                ('unit', models.CharField(db_column='Unit', max_length=50)),
                ('jobno', models.CharField(db_column='Jobno', max_length=50, primary_key=True, serialize=False)),
                ('tb', models.CharField(db_column='Tb', max_length=50)),
                ('clr', models.CharField(max_length=50)),
                ('bc', models.IntegerField()),
                ('sew', models.IntegerField()),
                ('che', models.IntegerField()),
                ('irn', models.IntegerField()),
                ('pack', models.IntegerField()),
                ('oth', models.IntegerField()),
                ('mist', models.IntegerField()),
                ('trstype_all', models.CharField(blank=True, max_length=80, null=True)),
                ('deldt', models.DateTimeField(db_column='DelDt')),
                ('merch', models.CharField(blank=True, db_column='MERCH', max_length=10, null=True)),
                ('ip', models.CharField(max_length=50)),
                ('orderimage', models.CharField(blank=True, db_column='OrderImage', max_length=4000, null=True)),
                ('tbimage', models.CharField(blank=True, db_column='TBImage', max_length=8000, null=True)),
                ('director_sample_order', models.CharField(blank=True, db_column='Director_Sample_Order', max_length=6, null=True)),
                ('finaldelvdate', models.CharField(blank=True, db_column='FinalDelvDate', max_length=4000, null=True)),
                ('final_year_delivery', models.CharField(blank=True, db_column='Final Year delivery', max_length=4000, null=True)),
                ('insdatenew', models.CharField(blank=True, db_column='insdateNew', max_length=4000, null=True)),
                ('c', models.IntegerField(db_column='C')),
            ],
            options={
                'db_table': 'Ord_stk',
                'managed': False,
            },
        ),
    ]
